language: node_js
node_js: '10'

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

os:
- linux
- osx

osx_image: xcode8.3

addons:
  apt:
    packages:
    - fakeroot
    - rpm

script:
- npm run make

deploy:
- provider: 'script'
  script: npm run publish
  skip_cleanup: true
  on:
    tags: true