language: node_js
node_js: '10'

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

os:
- linux
- osx

osx_image: xcode8.3

addons:
  apt:
    packages:
    - fakeroot
    - rpm

script:
- npm run make

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: out/make/*.{zip,deb,dmg}
  skip_cleanup: true
  on:
    repo: httptoolkit/httptoolkit-desktop
    tags: true