platform:
- x64

environment:
  nodejs_version: "10"

cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
- node_modules

branches:
  only:
  - master
  - /^v\d\.\d\.\d/

install:
- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
- cmd: appveyor-tools\secure-file -decrypt encrypted-win-certificate.pfx.enc -secret %CERTIFICATE_FILE_KEY%
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- npm update

build_script:
- node --version
- npm --version
- if %APPVEYOR_REPO_TAG% EQU false npm run make

deploy_script:
- IF %APPVEYOR_REPO_TAG% EQU true npm run publish